export const countryConfig = {
  US: { name: "United States", locale: "en-US" },
  DE: { name: "Germany", locale: "de-DE" },
  FR: { name: "France", locale: "fr-FR" },
  ES: { name: "Spain", locale: "es-ES" },
  IT: { name: "Italy", locale: "it-IT" },
  NL: { name: "Netherlands", locale: "nl-NL" },
  GB: { name: "United Kingdom", locale: "en-GB" },
  PL: { name: "Poland", locale: "pl-PL" },
  CH: { name: "Switzerland", locale: "de-CH" },
  JP: { name: "Japan", locale: "ja-JP" },
  CA: { name: "Canada", locale: "en-CA" },
  AU: { name: "Australia", locale: "en-AU" },
  NZ: { name: "New Zealand", locale: "en-NZ" },
  SE: { name: "Sweden", locale: "sv-SE" },
  NO: { name: "Norway", locale: "nb-NO" },
  DK: { name: "Denmark", locale: "da-DK" },
  CZ: { name: "Czech Republic", locale: "cs-CZ" },
  HU: { name: "Hungary", locale: "hu-HU" },
  AE: { name: "United Arab Emirates", locale: "ar-AE" },
};
